### PR TITLE
Add automated end to end test

### LINKED ISSUE #35: Add automated e2e testing
**Is your feature request related to a problem? Please describe.**

When developing git2consul-go, it would be nice to have an end to end test suite so you can easily ensure git2consul can still do the basic create-update-delete workflow for Consul KV pairs.

**Describe the solution you'd like**

A make target that would run an e2e test suite. The test should:

- [ ] Start a local consul dev server
- [ ] Run git2consul to create keys and confirm they are created
- [ ] Run git2consul to update keys and confirm they are changed
- [ ] Run git2consul to delete keys and confirm they are deleted

The documentation should also be updated explaining how to run the e2e tests and what it does. Probably should be included in developer documentation - Ref #28 

**Describe alternatives you've considered**

Continuing to manually test changes to git2consul.

**What version of git2consul-go are you using?**

<pre>
$ git2consul, version v0.1.2-dev (branch: master, revision: 9f404c06fe43479f3d81f237cee0ae93b3964905)
build date: 20200201-16:38:31
go version: go1.13.5
</pre>

### PR DESCRIPTION
**Pull request by vinny-sabatini**
**Description**

Add in the initial automated e2e test.

Fixes #35 

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [ ] ~Unit tests updated~
- [x] Documentation updated

### CODE REVIEW

**Comment by vinny-sabatini** [comment]
Putting this out there for initial review to get some feedback. See checklist for things I want to finish before this is ready for merging.

The "delete" test is currently failing, I'm not sure it's an issue with how I'm implementing the test or an issue with the code, so I am still investigating that.

**Comment by seanmalloy** [comment]
@vinny-sabatini I did a quick read of the code, and I didn't see find any major concerns. I'll need to do a more detailed review once this is no longer a WIP.

**Comment by vinny-sabatini** [comment]
TODO list before merging:
- [x] Add test to update kv pair
- [x] Cleanup commit history
- [x] Cleanup `TODOs` in `e2e_test.go`
- [ ] Change `e2e/e2e/genre` to `e2e/master/genre`
- [ ] Change branch to `master` in config files
- [ ] Get `delete` test case to work

**Comment by vinny-sabatini** [comment]
I think this PR is ready for review, I have removed the WIP label.
If others are ok with it, I will create a follow up issue to address the delete test case.

**Pull request merged**
